[tox]
requires = tox>=4
env_list = pytest, ruff

[testenv:pytest]
description = run unit tests with pytest
deps = pytest>=9
commands =
	pytest {posargs:tests}

[env.ruff]
description = lint and format with ruff
deps = ruff
commands =
	ruff check {posargs:.}
	ruff format {posargs:.}
