[tox]
requires = tox>=4
env_list = test, format, check

[testenv:test]
description = run unit tests with pytest
deps = pytest>=9
commands =
	pytest {posargs:tests}

[env.check]
description = lint with ruff
deps = ruff>=0.14
commands =
	ruff check .

[env.format]
description = format with ruff
deps = ruff>=0.14
commands =
	ruff format --check .
